name: OpenBao CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Install Docker Compose
        run: |
          sudo apt get update
          sudo apt install docker-compose

      - name: Build and test with Docker
        run: |
          docker-compose build
          docker-compose up -d
          # Wait for OpenBao to be ready
          sleep 10
          # Add your test commands here
          docker-compose down

  test-podman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman
      
      - name: Build and test with Podman
        run: |
          podman-compose build
          podman-compose up -d
          # Wait for OpenBao to be ready
          sleep 10
          # Add your test commands here
          podman-compose down

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Run linting
        run: |
          # Add your linting commands here
          echo "Add linting steps"

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'openbao:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' 